#!/usr/bin/env bash

THIS_DIR=$(cd $(dirname $0); pwd)
cd $THIS_DIR

function print_logo() {
	echo -e "\033[38;5;600m"
	echo -e "                      MaQzAfzar   [@ExtraTab]                        "
	echo -e "\n\e[36m"
}

if [ ! -f ./telegram-cli-1222 ]; then
    echo "telegram-cli-1222 not found"
    echo "Run ./install"
    exit 1
 fi

 
  print_logo
   echo -e "\033[38;5;208m"
   echo -e "                       MaQzAfzar   [@ExtraTab]                        "
   echo -e "\033[0;00m"
   echo -e "\e[36m"
   ./telegram-cli-1222 -s ./bot/extra-cli.lua
